theme = 'hugo-theme-relearn'
baseURL = "https://raougah.github.io/goshaders/"
relativeURLs = false
canonifyURLs = true
languageCode = 'en-us'
title = 'goshaders'
[caches]
  [caches.images]
    dir = ':cacheDir/images'
